# render.yaml  — backend
services:
  - type: web
    name: ocr-prototype-backend
    runtime: python
    branch: main
    # rootDir: backend   # uncomment & set if your backend is in a subfolder

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gevent -b 0.0.0.0:$PORT app:app

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CORS_ORIGIN
        value: https://photon-frontend.onrender.com   # change to your real frontend URL after deploy
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/ga.json

    healthCheckPath: /healthz
    autoDeploy: true
